// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package metrics

import (
	"context"
)

// iteratorForInsertBatch implements pgx.CopyFromSource.
type iteratorForInsertBatch struct {
	rows                 []InsertBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Ts,
		r.rows[0].Type,
		r.rows[0].Name,
		r.rows[0].Delta,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForInsertBatch) Err() error {
	return nil
}

func (q *Queries) InsertBatch(ctx context.Context, arg []InsertBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"metrics"}, []string{"ts", "type", "name", "delta", "value"}, &iteratorForInsertBatch{rows: arg})
}
