// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: misc.sql

package metrics

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :exec
SELECT 1
`

func (q *Queries) HealthCheck(ctx context.Context) error {
	_, err := q.db.Exec(ctx, healthCheck)
	return err
}
