// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package metrics

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Metric struct {
	ID    int64
	Ts    pgtype.Timestamp
	Type  string
	Name  string
	Delta pgtype.Int8
	Value pgtype.Float8
}
