// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package metrics

import (
	"time"
)

type Metric struct {
	ID    int64
	Ts    time.Time
	Type  string
	Name  string
	Delta *int64
	Value *float64
}
