// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package metrics

import (
	"context"
)

const getMetrics = `-- name: GetMetrics :many
SELECT id, ts, type, name, delta, value
FROM metrics
`

func (q *Queries) GetMetrics(ctx context.Context) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Type,
			&i.Name,
			&i.Delta,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
